### ISSUE TITLE
why dashboard doesn't get any response

### ISSUE THREAD

**Issue by thangta** [actions-on-google/smart-home-dashboard#23]
Hi, 

I don't see any response data in dashboard. Also, I don't see any request data in my server. 
I try many time, but still same error
pls help

![Capture](https://user-images.githubusercontent.com/13417944/60148691-511e3e00-97fc-11e9-96e1-ab1c0e848c3a.JPG)

**Comment by Fleker** [comment]
This sample does not directly interact with your server. It uses the Home Graph APIs to read the data that you've sent with *report state*.

**Comment by LIULi-VVET** [comment]
I encountered the same situation. 

this response code 500

http://myproject****.appspot.com/refresh?agentUserId=1749a8******************1845
{
error: "Internal Server Error"
exception: "java.lang.NullPointerException"
message: "No message available"
path: "/refresh"
status: 500
timestamp: 1561780421510
}

and other more  reponse code 403 Forbidden

GET http://api.giphy.com/v1/gifs/search?api_key=api-key&limit=1&rating=g&q=mydevice

this dashboard created in last year and successfully used, but can not be used now

**Comment by Fleker** [comment]
If you're getting a NPE in the backend, you should take a look at server logs to see what's going on, as that's unexpected.

The Giphy issue seems to be stemming from the fact that you're using `api-key`, which is a dummy value. But there should probably be a better way to present icons than using Giphy anyway.

**Comment by DriftingShadows** [comment]
> If you're getting a NPE in the backend, you should take a look at server logs to see what's going on, as that's unexpected.
> 
> The Giphy issue seems to be stemming from the fact that you're using `api-key`, which is a dummy value. But there should probably be a better way to present icons than using Giphy anyway.

I'm getting the same thing as @LIULi-VVET. I don't know how to decipher the error message I'm seeing in the AppEngine logs, apart from the fact that its getting a 500 error.

`[f~smart-home-action-reportstate/20190709t180141.419473170289254651].<stdout>: 2019-07-09 08:12:16.018 ERROR 1 --- [Request31AFF798] o.s.boot.web.support.ErrorPageFilter     : Forwarding to error page from request [/refresh] due to exception [null]

java.lang.NullPointerException: null
	at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkNotNull(Preconditions.java:191) ~[google-http-client-1.19.0.jar:1.19.0]
	at com.google.api.client.util.Preconditions.checkNotNull(Preconditions.java:127) ~[google-http-client-1.19.0.jar:1.19.0]
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:158) ~[google-auth-library-oauth2-http-0.9.0.jar:na]
	at com.google.auth.oauth2.GoogleCredentials.fromStream(GoogleCredentials.java:141) ~[google-auth-library-oauth2-http-0.9.0.jar:na]
	at com.google.homegraph.dashboard.controller.HomeGraphController.createConnection(HomeGraphController.java:97) ~[classes/:na]
	at com.google.homegraph.dashboard.controller.HomeGraphController.refresh(HomeGraphController.java:132) ~[classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_171-google-v7]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_171-google-v7]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_171-google-v7]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_171-google-v7]
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133) ~[spring-web-4.3.14.RELEASE.jar:4.3.14.RELEASE]
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97) ~[spring-webmvc-4.3.14.RELEASE.jar:4.3.14.RELEASE]`

**Comment by LIULi-VVET** [comment]
I have solved this problem.
The reason is that I used a **mismatched Project** dashboard to query status.
Another reason for the mistake is that I uploaded the **incorrect Json** file.

**Comment by DriftingShadows** [comment]
> I have solved this problem.
> The reason is that I used a **mismatched Project** dashboard to query status.
> Another reason for the mistake is that I uploaded the **incorrect Json** file.

Thanks for the response. What do you mean mismatched project? I've only uploaded one instance of the smart home dashboard on appengine and it used to work so I don't think I got it wrong. I'll perhaps try download the json file again and see. I wonder what I'm doing wrong.

**Comment by LIULi-VVET** [comment]
I have many different projects.
I think of the dashboard of another project as this
